---

- name: rstudio | install apt package
  tags:
    - package
  apt:
    deb: "{{ rstudio_url }}"

- name: rstudio | user group
  tags:
    - user
  group:
    name: "{{ rstudio_group }}"

- name: rstudio | user
  tags:
    - user
  user:
    name: "{{ rstudio_user }}"
    group: "{{ rstudio_group }}"
    password: "{{ rstudio_passwd | password_hash('sha512') }}"

- name: rstudio | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rstudio/{{ item }}"
  loop:
    - rserver.conf
    - rsession.conf
  notify: restart rstudio

- name: rstudio | nginx config
  include_role:
    name: nginx
    tasks_from: site.yml
  loop: [ rstudio ]

- name: rstudio | service
  tags:
    - service
  service:
    name: rstudio-server
    state: started
    enabled: yes

